language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn install
  - yarn run build

deploy:
  - provider: s3
    skip_cleanup: true
    keep-history: true
    local_dir: build
    access_key_id: "AKIAVBLQBN5YERU65A43"
    secret_access_key: "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"
    bucket: "viewer.earthsystemdatalab.net"
    on:
      branch: master
