language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  directories:
    - node_modules

env:
  - XCUBE_VIEWER_VERSION="0.4.2"

script:
  - wget https://github.com/dcs4cop/xcube-viewer/archive/v${XCUBE_VIEWER_VERSION}.tar.gz
  - tar xvf v${XCUBE_VIEWER_VERSION}.tar.gz
  - cp .env xcube-viewer-${XCUBE_VIEWER_VERSION}
  - cd xcube-viewer-${XCUBE_VIEWER_VERSION}
  - yarn install
  - yarn run build

deploy:
  - provider: s3
    skip_cleanup: true
    keep-history: true
    local_dir: build
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: "eu-central-1"
    endpoint: "s3.eu-central-1.amazonaws.com"
    bucket: "viewer.earthsystemdatalab.net"
    acl: public_read
    on:
      branch: master
