language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn install
  - yarn run build
  #- yarn run test
after_success:
  - codecov

deploy:
  - provider: pages
    skip_cleanup: true
    target_branch: gh-pages
    github_token: $GITHUB_TOKEN
    repo: esa-esdl/esa-esdl.github.io
    target-branch: master
    on:
      branch: master
