language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - cd xcube-viewer
  - cp ../config.ts src/
  - cp ../public/* public
  - yarn install
  - yarn run build
  #- yarn run test
after_success:
  - codecov

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: build
    on:
      branch: dzelge_submodule
