language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn install
  - yarn run build

deploy:
  - provider: s3
    skip_cleanup: true
    keep-history: true
    local_dir: build
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: "eu-central-1"
    endpoint: "s3.eu-central-1.amazonaws.com"
    bucket: "viewer.earthsystemdatalab.net"
    on:
      branch: master
